---
- name: Install Apache
  hosts: all
  become: true
  gather_facts: yes


  vars:
    apache_package: apache2
    apache_service: apache2

  handlers:
    - name: restart apache2
      service:
        name: "{{ apache_package }}"
        state: restarted

  pre_tasks:
    - name: Override apache vars for red hat
      set_fact:
        apache_package: httpd
        apache_service: httpd
      when: ansible_os_family == 'RedHat'

  tasks:
    - name: "install {{ apache_package }}"
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Copy a web page
      copy:
        content: |
          <html>
          <head><title>Hello World</title></head>
          <body>Hello World!</body>
          </html>
        
        dest: "/var/www/html/index.html"
      notify: restart apache2
        

    - name: Ensure apache is running and starts at boot
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true