---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
 name: docker
lint: |
  set -e
  yamlint .
  ansible-lint 
platforms:

  - name: instance
    image: geerlingguy/docker-centos8-ansible:latest
    privileged: true
    command: " "
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

    pre_build_image: true 
    
provisioner:
    name: ansible
verifier:
    name: ansible