- name: Verify
  hosts: all
  become: true
  
  tasks:
    - name: Verify Apache is serving web request
      uri:
        url: http://localhost/
        status_code: 200
        # return_content: true